# Generated by Django 3.0.6 on 2020-05-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkTitle', models.CharField(max_length=100)),
                ('linkUrl', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberName', models.CharField(max_length=100)),
                ('memberPhone', models.CharField(max_length=20)),
                ('memberMail', models.EmailField(max_length=254)),
                ('memberDescription', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Motd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motdText', models.CharField(max_length=1000)),
                ('motdSource', models.CharField(max_length=100)),
            ],
        ),
    ]
