# Generated by Django 3.0.6 on 2020-05-26 00:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='memberBirth',
            field=models.DateField(default=datetime.date(2020, 5, 26), verbose_name='Birthday'),
        ),
    ]
