# Generated by Django 3.0.6 on 2020-05-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cwPoll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='pollInDetail',
            field=models.CharField(default=' ', max_length=500),
        ),
    ]
